######################################################################
# Automatically generated by qmake (3.1) Mon Mar 16 19:05:53 2020
######################################################################

TEMPLATE = app
TARGET = 9.3
INCLUDEPATH += .

QT += gui widgets
CONFIG += release
# Input
HEADERS += calcDialog.h
SOURCES += calc.cpp calcDialog.cpp
