######################################################################
# Automatically generated by qmake (3.1) Tue Mar 17 12:23:31 2020
######################################################################

TEMPLATE = app
TARGET = 9.4
INCLUDEPATH += .

QT += gui widgets
CONFIG += release
DEFINES += QT_DEPRECATED_WARNINGS


HEADERS += StrDialog.h
SOURCES += main.cpp StrDialog.cpp
