######################################################################
# Automatically generated by qmake (3.1) Sat Mar 14 21:21:09 2020
######################################################################

TEMPLATE = app
TARGET = lib9
INCLUDEPATH += .

QT += gui widgets
DEFINES += QT_DEPRECATED_WARNINGS

SOURCES += main.cpp
